server:
  port: 8031
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
  http2:
    enabled: true
  servlet:
    encoding:
      force-response: true

spring:
  application:
    name: carog-server
  profiles:
    default: local

  datasource:
    read:
      jdbc-url: ENC(3/pqDxW8E6Tslk9b8JGgV677PgJasc6zik7ZhIfQgjPiLkAbyarpGhxILbuE8U8TcANz1wTmPdXhEIauEn7RCmt9fvEk55t0TBnG4V44+lESoAMDZQ6UJKZA8M8bexXYBqPtwPScYvZIK6vr+54l9UQR74GWNk9iWMCdy9R3JCv853f9fX8KOyfv/iNhaPQ3)
      username: ENC(gEQztSYVeNp5irJThBP4RrUNKdKFuIR+/D0g+d2mfNJ94y/kkyytua9QSPlLCMcc)
      password: ENC(XGHNHomfOgQd5F8qTNuDwRC6jPKGhtxUS41NNlW1hq5yrX5JESye9fe4qF/BaqXf)
      minimum-idle: 5
      maximum-pool-size: 10
      pool-name: READ-POOL-CAROG
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      read-only: true
      auto-commit: true
    write:
      jdbc-url: ENC(P9hNTKq7MpKB1SCd8qRDeoHfrF/yyPx1P8uLuDLZtoIuTdpsfLUhXhyRrIa7eopQZ1G4y4B4zP/9Cc7tsJH+dy0s/Ac5a84LSMHHVRSukbqxtY6Tba4vyFtcJ7m9w6PUa5HpD49TJpUyGkP5RAk4z7eWuR1s+yQWdCeNnzrPrYGQyN/m2Ikq/6wSH9MiCwmx)
      username: ENC(hovbLIgUb4eS8aojTsjrFFpBfQ4rwaFxQ12vgxFAwD8xUpVYphUsYRjkxJogO4R/)
      password: ENC(a+HCoJREPzdFGH9JbSNJRj9sc8cIKoT3fg5j7I75bjnu+3WNHwcK3leq+oJSnuvy)
      minimum-idle: 5
      maximum-pool-size: 10
      pool-name: WRITE-POOL-CAROG
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: true
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
          time_zone: Asia/Seoul

  data:
    web:
      pageable:
        one-indexed-parameters: true

    redis:
      username: ENC(JbgnxWFB2P4gTkfLQkBghRBc+cWCTQPdvnfI2Oc1DMEJMUXrJwUi6S3RgKzNxsag)
      password: ENC(9jaRsFPFOY0kr6JmqrKKrZ7YlJpkyj56orpaUGpUr3//vgLcZhAal63TY766+/i9)
      database: ENC(qil8EBsALcr7OFzJsgdFR/tMI4+siIKMi2tDYY4f6H5ujDr6oWcvBnEv3aMH5j+V)
      lettuce:
        pool:
          min-idle: 3
          max-idle: 10
          max-active: 10
      sentinel:
        master: ENC(p/OFG+RzIco5y9PKBJpCHU9eb65XDlVsfqndeWMfvlh9kaatWwXtkBCAso7ZsGbb)
        nodes:
          - ENC(e9+rFWfloqnAn+mCqq04mdHgN0bbn/RGtoutBAHtf5Hmq9GsciENPbdk4CAFb+Cb0c2P7v9h/qOKe04S/id9VA==)
          - ENC(j3QIpVfXTh6kseAqTkTqbj6hfnLP5gDvxzLMrdka0JvlnCf1gRsJ0dux0/0uD1RyCnMxokDHOvjjWl4VvBI2tg==)
          - ENC(htsta8Vme9ikw+1AT0hki07NoD4pWAgidlePqW6Q0YLTHKIAI2alANa4Uee/eOYDsoEeDz3T0YqLM5rg6QVIOw==)
        username: ENC(smAbCpAHZyKC6RJGAyoFkma0/p+YWTKVTL0v6Ff1yxcWkgLRPDouHeAB0Pjt1INZ)
        password: ENC(l/RupNzQ1yVxbSyr1r6/IyLR1Gs/2po87TRQfP3uGpyY4qP2QVAD4IndJO5uo3z6)

  output:
    ansi:
      enabled: always

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

kakao:
  client-id: ENC(TmYtXjdZybZd1ik9ipv+AyMlmuosasSxxqcSHX8E4RNvGjzoEbKCh2Cd70J6dJc/Y7MRiCxHE8qIjHc59bVIbPQz2yP0RxY+ij12Rnz6KP4=)
  client-secret: ENC(KdDfEtjCGql7QqnIEbEisC7TTgmPlgJ7oV0h3i+yyhlT/oY3yQP4CA4sC8vCblNXzETu2zS/Dro0qxBtn4D/SqumkyTB5kl0QBfOH9v116c=)

logging:
  config: classpath:/logback/spring-logback.xml

jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    key-obtention-iterations: 10000
    pool-size: 1

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    shutdown:
      access: none
    health:
      show-details: always
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true