server:
  port: 8031
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
  http2:
    enabled: true
  servlet:
    encoding:
      force-response: true

spring:
  application:
    name: carog-server
  profiles:
    default: local

  datasource:
    read:
      jdbc-url: ENC(9F5d20uw+kWKdcT8UbpLeqGVZuq5XOwzR1Yy6aW9ofn9BXt77zUq5XL1hYtS78qa55tCL0E4kwuYuzVCAf9ciJsBv+69hB3Sz++23X2VRhd7BcD70OLx5QhuBeFOCS8XenRYNW+eDgBvdL0FJ4f5Va1jEZRP+QQJzM//IdpIEgFOvSjpgbd7q1ZX2KcHquha)
      username: ENC(MAIODXlR14CXMY36bWwbpbs/G30g+L6qxAd+d5wIBkNqYfWadv8HFGG154sRd8eP)
      password: ENC(qMQKH8sPuOb6hA/4znTLs24xptNJ9yCunJ3xHir60Vtq2z4eCeghI6zip0dUH8Vo)
      minimum-idle: 5
      maximum-pool-size: 10
      pool-name: READ-POOL-CAROG
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      read-only: true
      auto-commit: true
    write:
      jdbc-url: ENC(wNpcwyV9NAJZ2gShGObKe6cmOSnnHasikufeve9Jx3PSfDh5nkhQl8s5XND1g/FZvMaNcYjdG6Qkrtw60hCVfcNvuew5zAufDIOymNxNGLJ7zEQTW+YLO7p0t5p1r/oD8Eb9pQYox4yCSVyyeFnzXG0XYC/nubxxivZnRrSIiGbbReJBXbBDdgBhcH0ZhI/a)
      username: ENC(5qGdm3FMJhIpS3NpM3q2vWJvohpev5S3HAedFeTpSfVKOsZxhqlbWNlmHLzkuFGA)
      password: ENC(D9rPVMWGzxFBKewaTkjVrWKvaZYsbLcBqsI9AMSCG6Z2pLU5rZJkQnUQwdjTYK6l)
      minimum-idle: 5
      maximum-pool-size: 10
      pool-name: WRITE-POOL-CAROG
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: true
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
          time_zone: Asia/Seoul

  data:
    web:
      pageable:
        one-indexed-parameters: true

    redis:
      password: ENC(M6Otamnhj2EHPmva6+/t7GWJmWgXlem6Xf7UiQpiJiDgN7IQM6t21gzfsfVq2ZE6)
      database: ENC(fIHSh2t81hjbpgg7CLoybmiV80N9unssEmVdtKp8Pkuk+culzFtnEVC18HdyOj4I)
      lettuce:
        pool:
          min-idle: 3
          max-idle: 10
          max-active: 10
      sentinel:
        master: ENC(dY4uQSaRCtuwHJx0+LrM01SrlFZLdoFo5kiseyQHcG9tchQkRgMpmtqq2z8BfA4g)
        nodes:
          - ENC(HCA5wJKc4fH2HID51w09sK/JDziNqGUA4ftwW1SrouUOCe2rl32IuIP2SYKJG+e8VnYqnFJkCbVZyu/EwxADuA==)
          - ENC(P9BeRdbKzBva2JvuYMwXmqGm72PSDHIjg+j+uCHEDHPgTYWd+6uwAuUj/7TtKk1/TN/uyd+2mtkaG00DDbmo4Q==)
          - ENC(caHG8PhAtS5kHfXZ07L3mHtABacwdltx9SATsRUSwcJYPpWaREcW6YzrcB/uL+fPsX6ZSPtyzCI6eVto9J+/Zw==)
        password: ENC(TBcSM9XXHsBrs6UWTRJrAi7noJ3xtr110cWC2KKAixkMbPrO/3faQBjZdyl5IW1f)

  output:
    ansi:
      enabled: always

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

kakao:
  client-id: ENC(uEWoLMtpGcJ+hUNi4TjLI7RhElv87QY18FLBL4szs7U6h0VIRgtN07cG3aHiJww9WXF24ih9YeMbHSBw0asP2aKi64RJhhuMZoVQVPFrp7E=)
  client-secret: ENC(eh+Qbyuc40ROq2coiUV33FskKRbpOZNpqjxyZY0cfQBCWI86bw88D8ghSBGIMWQK42bOggeeVISBF0ImyibDnO2/A6zn6RptPGpbQYFwwgM=)

logging:
  config: classpath:/logback/spring-logback.xml

jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    key-obtention-iterations: 10000
    pool-size: 1

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    shutdown:
      access: none
    health:
      show-details: always
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true