server:
  port: 8030

spring:
  application:
    name: carog_server
  profiles:
    default: local

  datasource:
    hikari:
      jdbc-url: ENC(u7IgG7S24mxEZ57xwhSkS2x2RRtI6n3LFewGJ3ZMt6eMN6sxyrgRYXgN/UAAQSMMMT/MdJ9BU5h3FVrE8QQZuzcq3JYoF/wBNgU3I0wmIQ2z1WCjiDIRJwQemuxbiZ+9AHtHOuJezNtIaJSKreXcBRzNunMhpEYMeXgrVMJy3h8WAaebrTVkJJ3Twz2B+U7U)
      username: ENC(n1giSgZSOJvqPoUxUGcZ9cfJLeX4NrI8lN9BgDTOAIXpczzQXLxY6u8KkLWZ1DGJ)
      password: ENC(C0j0j1ja+ZO6Zn+1ppOFLVZlITg25UYvclAkjxcDPDQqcO1NYy8tylUlnfUKTRyG)
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      minimum-idle: 10
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      pool-name: POOL-CAROG
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: true
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
          time_zone: Asia/Seoul

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ENC(fhGGS/92iVUCQIPw8CO0L42iZ05x000lZDr3pTvHkVFQpYzeTVXMulRqkaWqPvCL6sHWwCaUPRelIdsIlG+N4ZAALeTXNiur5IelBuRb9qU=)
            client-secret: ENC(bWCKseqIdxkD+Jf84JiXif99GoT0b6wMtzis8j40qTK0WphNI0YNeGhcA70WwYJxuHpS5Vm5fJNEihEI7gczr+NarRkDreE+0rxQAJKKHas=)
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
          naver:
            client-name: naver
            client-id: ENC(16rGw4pJdn4igzo24CBwRulTYjfIuvZITdTvkn8NCivbbgs7yDhGZC9TUtGxNHgxDZY1fjmUzU4VLG2ueR543A==)
            client-secret: ENC(3hZ+uAK2FHCQ/fN+IRJcsqCgjxyxKD6FDrZTdLltx9VBS3lX68p/QZsxAF5PA4qD)
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  config: classpath:/logback/spring-logback.xml

jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    key-obtention-iterations: 10000
    pool-size: 1