server:
  port: 8030
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
  http2:
    enabled: true
  servlet:
    encoding:
      force-response: true

spring:
  application:
    name: carog-server
  profiles:
    default: local

  datasource:
    read:
      jdbc-url: ENC(tgiwRMHX12WFmnMvYtINOMIMbvu2CjzbJSTyIglgKDozIaO4TU1uqpmZicO60MXp/x+I6PECQxTpbHmcKl25dNxXT6IyLp5ddwTmT4EZXUK3wemMx3LWQyAXUDT3rLiZc8CL4WiblR+xI7cNdk+X1Sz2O97sZzndjZRs6YSq+OCChB/FBQlCcCp6uMuwYwSo)
      username: ENC(w0o6vFFJg9jWmfkoKVdUR11NhiLRlPoQ34wOZXJyfO40Vxaa8lOdndjo6nvtJ9Yn)
      password: ENC(MT3FpTIE+yORc/CZ0tdapPwv1vFX+d1Y56yUohrO7jPUje+2pDXQgJqod8RKCPqR)
      minimum-idle: 10
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      pool-name: READ-POOL-CAROG
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      read-only: true
      auto-commit: true
    write:
      jdbc-url: ENC(OSfQn5fPwuFVXhL59QRgyNDMymUJXpXZYgFngiTmnTRpg+6VaU3S18tj/rGkktTlIbRQWG9fUJ1uApzdO3Yh3+6mraNCVP0m4Wmt8wY/2ASS6aEsXE6iTcPt5ETQl9xcdmyTRQIu0xJhEVf3/sDA9cD9bhFUGKC7T7LNW9WWQzrvcv3A29azodDRh+j2/njx)
      username: ENC(K1hM9KNlWGO3qVvrThLUZ+kX17tuneUXGL87sEkYQ8vqXWKoB88TaRDss0u4Yr0W)
      password: ENC(s/Pat+EmR8Rh5AeTNB2s84GzTp/KcYN4j6kKi5P0jqV2cONzzjceGFyWQL9mPXSH)
      minimum-idle: 10
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      pool-name: WRITE-POOL-CAROG
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: true
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
          time_zone: Asia/Seoul

  data:
    web:
      pageable:
        one-indexed-parameters: true

    redis:
      username: ENC(IMYEwU5/lTq8GOlK/qVPlp/s3mGt86kB0nONcuamqkwxY3nYukjiMebBmrVK51im)
      password: ENC(Ghv2hJmAH+U/Ckl1WThDjmGwze9HraZjCnXx0VHoF1/8PuiQVqyrcSucao+aHA2m)
      database: ENC(iQhtR1nvi/+zoAM/2BNTIwuOjyf1toy/Es8VcEPs3hV1RvqLIYzKtuSaD0LF98/X)
      lettuce:
        pool:
          min-idle: 3
          max-idle: 10
          max-active: 10
      sentinel:
        master: ENC(ioEeFFsJ9A/u9O0uUfYME9f3q9Fr5oJMjRU+ExJ2dD0CtwO0S7DlWEVIWaSbmpxw)
        nodes:
          - ENC(7vF1lWPiNdBsZ19RwRiSXllAOh/+RaktsHqPySM7EvIBBkhXw96doFrw+hbzJzCvrR+We1Q+9RiM/F/tKv/5hg==)
          - ENC(SGrOoVE3kAQAGKHKEWsVokQ7O4Hxw3Su3I8blp1OSL5bsDiG75gfXa2Re0LHbZuf6Lr5rUpWuKpSM6YYIrRO9g==)
          - ENC(YsekhDC3Ooa30L83WYc86K7irNSiqr/i+Tmtd73lJgWIWyklP95/d5PWPAn1tFGJOZBXDVCIcxg7zbxEmFIC+A==)
        username: ENC(Vxs0tGrrfBBb0+HS8sGPfPDqd+glg20mNLWT/tR9MbqU/XaWrexKStGCQQJJXGnk)
        password: ENC(Oa4RaJZn2irycXlnXjcPITdu0nHpUnNRIUliyc5s8GLqIvl5ZmP4SQA/DwqZdlQI)

  output:
    ansi:
      enabled: always

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

kakao:
  client-id: ENC(wHkPf2B26YUhQBeRPvk2M+RMzGgwnc88rfo+CkgzpgOSI8xKwREWBFdY48J2x0hVaPKaZTdsJle0d9ceH7Qux0ba7+5bg9yRUKTXPQXGELM=)
  client-secret: ENC(8WP1oicNsu50O4EMIKdfs3wX4hbYpqBLcor0/Owi14QX6JTAskFNK3wo3QldDuWPpRiGzU+kRS8BVNk9lXRP+uo7k5y+j/lT0Tujpx3kgtI=)
  redirect-uri: "http://localhost:3003/auth/login/kakao"

logging:
  config: classpath:/logback/spring-logback.xml

jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    key-obtention-iterations: 10000
    pool-size: 1

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    shutdown:
      access: none
    health:
      show-details: always
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

---
server:
  port: 8031

spring:
  config:
    activate:
      on-profile: main

  datasource:
    read:
      jdbc-url: ENC(X08PwdyyhbtmP5V96XiLbwnlR4VSMeklD4fPhc8aK7/Jq/hVXGpDATyNLPvSvfdN/cKbm6djKrBdOZa+kBVZmOqoCUTl9mablcGKB2c8j8jTX3NsbSYQa1Y4cmldXMX8KnEjkG9DZOT+tgHpzDb0UXQf421Yun8FgxnwzKQZF7Fvsz24IVDTbHJvQv16ADXv)
      username: ENC(pOGY7e4zRv0hfeAMu0sCoTnLQZMKR/TNLtJnrVl3NbuzlKCneWvPggb119g6ks+5)
      password: ENC(uCUtr5UYROen4+VV5QI0RF1FFXHvDqa0xP7CU+GMK2Erh4JgKUIxewAY7ztnzXFP)
      minimum-idle: 10
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      pool-name: READ-POOL-CAROG
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      read-only: true
      auto-commit: true
    write:
      jdbc-url: ENC(ih+bdM2dPu9tBJyynnVHi2Nl90729lYn3Axfh8jQdCoSwBmHDMlyf/dq410vcx7MpnUQBkqtnE+dRN8Fssjg3JYnNEubO7X/iU/gXo1F8jRzz+gXggLbseSu/3ybUZLURwNO2MIc6b+Pqv46rKjASPCpsDXDtvswzdsi6UcQsi6ThnuFvFPvLYsZzXWcTG6x)
      username: ENC(NsEI/XRQMYjBIDHE3WM1oYfQ9r+EXLlqVxbbd/TbL4drKQuXTzMw6JHm0GF8+UmP)
      password: ENC(NULQEEDA5oDxp9o1vUSieZ/8Otyg8OZNF7L52qH5QJ4O1yRWrwNWDZtf4g3VgQm6)
      minimum-idle: 10
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      pool-name: WRITE-POOL-CAROG
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  data:
    redis:
      username: ENC(9XrDO0kwCMev4fQvpeVOJGtMIbKkocXdbE6CSPXuhzCT32412cUCyeFGTZ/di0KD)
      password: ENC(2wBsZ7PAn2+STECpEh/1F3DaN7aaST+XoAZdh3i5Z50I0qUoMaEmq/mLOwozHX+V)
      database: ENC(mfmd9sqDBGQSbuoSIfUt+1UQNPTkAZ4JqFA9WVFOd7blWSGOZs1pcCQeRuB6qtDf)
      lettuce:
        pool:
          min-idle: 3
          max-idle: 10
          max-active: 10
      sentinel:
        master: ENC(cp84VgZuMRjbpp9flLagS3oKxSqq4Q3CcjPmz2S89P0cunkxM+GsnfSVR0T1EE2Z)
        nodes:
          - ENC(IqWsQVFA1GXv7jiEuhAJaQiTrdAsZGv9BLmQ2LqN+blDfj/mjkohaQz10YOsKQPDEpJBzmzWU4GYTj82hd8zxg==)
          - ENC(IKHydiCUeg7t2gQUq0kNsNuvbelQiy0L3feQ/ZhgSP/xMXmB5PsPrJI919NvQRrrIBscc8NyoJE07GXJFabLew==)
          - ENC(zaI5wc/LgkZ/QBSLEuVHUx74CSLWoGpoGMmfVa70unSEuoTogiNr/kZKqV6KdEe8r3eSJdML0VHPiIDK0bTZIw==)
        username: ENC(g+vpUf5elK2zYc+XB9p+Ux3dlicZXESpCCtIjgmdO7W1X6N+EKZmOKlZ5cNwNA00)
        password: ENC(R2JCOAPbVAhDuAcRtQA6a/dFdg4XevAuCDRUEFQJtvAJxw75S/Ky8KMGbN5Z4l9B)

kakao:
  redirect-uri: "http://localhost:3000/auth/login/kakao"