name: Build Spring Boot
on:
  pull_request_review:
    types: [submitted]
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: local
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}

    steps:
      # 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # JDK 21 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'amazoncorretto'
          cache: 'gradle'

      # Gradle 캐시 설정
      - name: gradlew executable
        run: chmod +x gradlew

      # GitHub Container Registry 로그인
      - name: Login GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Jib 빌드 실행
      - name: Build with Jib
        run: ./gradlew jib --no-daemon
        env:
          JAVA_TOOL_OPTIONS: -Dspring.profiles.active=${{ env.SPRING_PROFILES_ACTIVE }} -Djwt.secret=${{ env.JWT_SECRET }} -Djasypt.encryptor.password=${{ env.JASYPT_ENCRYPTOR_PASSWORD }}
          JIB_TO_IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}